Adds a python script that will create a CSV file with provenance in…
CONP-PCNO/conp-dataset pull request #426
Opened 2020-09-18 19:37 UTC by cmadjar

## Description

This is the second time now that I have to provide a spreadsheet summary of the datasets provenance for reporting purposes. Now that we have the wonderful `origin` fields in the `extraProperties` of the DATS.json files for almost all datasets, a script could be created to generate such a spreadsheet (CSV).

To create the CSV file with the dataset provenance summary, execute the `create_data_provenance_summary.py` script with option `-d <path to conp-dataset>`. Running the script with option `-h` will display how to use the script

```bash
$ python create_data_provenance_summary.py -h

This tool facilitates the aggregation of data provenance for reporting purposes. It will read DATS files and print out a summary of data provenance based on the `origin` fields present in the DATS.json files of every dataset present in conp-dataset directory.

usage  : python create_data_provenance_summary.py -d <conp-dataset directory path>

options: 
	-d: path to the conp-dataset directory to parse
```

Once the script has finished running, it will have created a `dataset_provenance_<date>.csv` which will contain the following information for example:
| Dataset                                                                                                                                             | Principal Investigator | Consortium                                 | Institution                                   | City      | Province         | Country        |
|-----------------------------------------------------------------------------------------------------------------------------------------------------|------------------------|--------------------------------------------|-----------------------------------------------|-----------|------------------|----------------|
| BigBrain dataset                                                                                                                                    |                        | BigBrain project                           |                                               |           |                  |                |
| PREVENT-AD open data in BIDS format                                                                                                                 |                        | PREVENT-AD Research Group                  |                                               | Montreal  | Quebec           | Canada         |
| Multimodal data with wide-field GCaMP imaging                                                                                                       |                        |                                            |                                               |           |                  |                |
| BigBrain dataset - 3D Surfaces (derived dataset)                                                                                                    |                        | BigBrain project                           |                                               |           |                  |                |
| Intracellular Recordings of Murine Neocortical Neurons                                                                                              |                        |                                            |                                               |           |                  |                |
| McGill EMC: RNA-seq experiment from human brain sample                                                                                              |                        |                                            | McGill EMC                                    | Montreal  | Quebec           | Canada         |
| Neurodevelopmental Disorders Priority Setting Partnership                                                                                           |                        |                                            | Ontario Brain Institute                       | Toronto   | Ontario          | Canada         |
| OpenPain cbp_resting                                                                                                                                |                        |                                            | Northwestern University                       | Evanston  | Illinois         | USA            |
| OpenPain BrainNetworkChange_Mano                                                                                                                    |                        |                                            | USA                                           | Evanston  | Illinois         |                |
| OpenPain subacute_longitudinal_study                                                                                                                |                        |                                            | Northwestern University                       | Evanston  | Ontario          | USA            |
| OpenPain thermal                                                                                                                                    |                        |                                            | Northwestern University                       | Evanston  | Illinois         | USA            |
| OpenPain placebo_1                                                                                                                                  |                        |                                            | Northwestern University                       | Evanston  | Illinois         | USA            |
| OpenPain placebo_predict_tetreault                                                                                                                  |                        |                                            | Northwestern University                       | Evanston  | Illinois         | USA            |
| Systematic phenomics analysis of autism-associated genes reveals parallel networks underlying reversible impairments in habituation                 |                        |                                            | University of British Columbia                | Vancouver | British Columbia | Canada         |
| High Resolution Magnetic Resonance Imaging of Mouse Model related to Autism                                                                         |                        |                                            |                                               |           |                  |                |
| Multicenter Single Subject Human MRI Phantom                                                                                                        | Alan C. Evans          |                                            |                                               |           |                  |                |
| Visual working memory: Study of Task fMRI and Behavioural response                                                                                  |                        |                                            | Imperial College London                       | London    |                  | United Kingdom |
| A Transcriptomic Atlas of Mouse Neocortical Layers                                                                                                  | Chris P. Ponting       |                                            | Oxford University                             | Oxford    |                  | United Kingdom |
| Homo sapiens reference genome sequences                                                                                                             |                        | Genome Reference Consortium                |                                               |           |                  |                |
| Mus musculus reference genome sequence                                                                                                              |    [...]

2020-09-18 20:49 UTC, cmadjar commented
@emmetaobrien @glatard ready for review.

2020-09-29 13:54 UTC, cmadjar commented
@zxenia could I ask you to review and test this?

2020-09-29 17:35 UTC, zxenia commented
@cmadjar yes, I can do it

2020-10-07 16:42 UTC, zxenia requested changes
@cmadjar I tested it, please see my comments. Could you also add a basic README file in `data_aggregation_summary_scripts` dir with the info on how to run the script? Thanks!

2020-10-07 16:42 UTC, zxenia commented on scripts/data_aggregation_summary_scripts/create_data_provenance_summary.py
> +        values_dict[extra_property['category']] = extra_property['values'][0]['value']
Now it only takes first value in the list. We can have use cases where `'origin_institution'` contains more than one institution,
can be fixed with
`values_dict[extra_property['category']] = ", ".join(str(value) for value in [exp["value"] for exp in extra_property["values"]])`

2020-10-07 16:42 UTC, zxenia commented on scripts/data_aggregation_summary_scripts/create_data_provenance_summary.py
> +    with open(dats_path) as dats_file:
I had to specify encoding here: `with open(dats_path, encoding="utf8")`

2020-10-08 14:26 UTC, cmadjar commented
@zxenia thank you for you review!! I added the README file and integrated your comments. Ready for another review. Thank you!!

2020-10-08 15:59 UTC, zxenia approved these changes

2020-10-08 15:59 UTC, zxenia commented
Looks good!

2020-10-15 16:14 UTC, emmetaobrien approved these changes
All seems good to me.

2020-10-15 16:14 UTC, merged