Remove and Reorder pre-commit hooks
CONP-PCNO/conp-dataset pull request #590
Opened 2021-04-16 22:55 UTC by mathdugre

## Description

The current pre-commit config as some hook conflicting with each other.
This PR solves this issue by re-ordering the hooks in a non-conflicting way. This was tested by using a previous version of the repo (cab6b33dc9fdfdf2adf39fcecdc7b619baf8a13) and running the new configuration on it. The files auto-formatted now pass on the second execution.

Additionally this PR temporarily disable `mypy` and `pydocstyle` hooks while the code does not abide their rules yet. This in done in order to have the linting workflow succeed PRs.

2021-04-16 22:59 UTC, mathdugre commented
@joeyzhou98, do you have feedback on this?

@glatard, Once this is merged it should fix the issues Joey had in #589

2021-04-16 23:11 UTC, joeyzhou98 requested changes

2021-04-16 23:11 UTC, joeyzhou98 commented on tests/requirements.txt
> +gitpython==3.1.7
I think you repeated a package here

2021-04-16 23:53 UTC, joeyzhou98 approved these changes

2021-04-16 23:54 UTC, mathdugre commented on tests/requirements.txt
> +gitpython==3.1.7
Thank you, I removed the duplicate

2021-04-19 14:17 UTC, cmadjar approved these changes

2021-04-19 14:17 UTC, merged