refseq_Mus_musculus update
CONP-PCNO/conp-dataset pull request #823
Opened 2023-04-14 19:55 UTC by emmetaobrien

This PR updates the `refseq_Mus_musculus` dataset again as the source dataset updated twice in quick succession.

2023-04-14 20:02 UTC, tkkuehn reviewed
I confirmed that I can get both files in the dataset. A quick question before approving though.

2023-04-14 20:11 UTC, emmetaobrien commented on .gitmodules
> +	url = https://github.com/emmetaobrien/refseq_Mus_musculus.git
No we don't, that was an error and I will correct it now.

2023-04-14 20:21 UTC, emmetaobrien commented on .gitmodules
> +	url = https://github.com/emmetaobrien/refseq_Mus_musculus.git
Submodule now updated to point to the version in conpdatasets.

2023-04-14 20:53 UTC, tkkuehn requested changes
There appears to be something wrong with the subdataset now -- `datalad get` any of the two files does nothing and `git-annex whereis` on those files prompts for a `git annex init`

2023-04-14 20:56 UTC, tkkuehn commented
Ah, I think the issue is the `git-annex` branch hasn't been pushed to github

2023-04-17 18:04 UTC, emmetaobrien commented
This now looks to be fixed.

2023-04-17 19:58 UTC, merged